### ISSUE TITLE
The user should be able to start a game via the lobby

### ISSUE THREAD

**Issue by derechtenap** [derechtenap/dartmate#13]
**Is your feature request related to a problem? Please describe.**
Currently, the user is not able to start a game via the lobby. Meaning there is no way to start a game.

**Describe the solution you'd like**
I would like to request the feature where the user can start a game directly from the lobby. This will make the user experience more seamless and efficient. Ideally, there would be a button or link in the lobby that the user can click on to start a game.

**Describe alternatives you've considered**
One alternative solution would be to add a menu option in the navigation bar to start a game. However, I believe this would still require users to navigate away from the lobby, which is not ideal.

## Tasks

- [x] Add a new button or link to the lobby
- [x] When the user clicks on "Start a Game", navigate to the game setup screen where they can select the game type, players, and other options
- [x] Implement the logic to create a new game instance based on the user's selections
- [x] Ensure that the game instance is properly initialized with the selected game type, players, and options
- [x] Test the new feature thoroughly to ensure it is working as intended
